// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-4KrLgIcTQLUSJVm_L8MyAl_TPz5js8E',
    appId: '1:261106161508:web:e53955dd3970e373dd4c71',
    messagingSenderId: '261106161508',
    projectId: 'aquaminder-ft',
    authDomain: 'aquaminder-ft.firebaseapp.com',
    storageBucket: 'aquaminder-ft.appspot.com',
    measurementId: 'G-WDWC1K3W9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbdmX9lc_sYVf1EfGtQMNnraULQjqb3_c',
    appId: '1:261106161508:android:e6c171966ee546ccdd4c71',
    messagingSenderId: '261106161508',
    projectId: 'aquaminder-ft',
    storageBucket: 'aquaminder-ft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6UjsaBUhpR4ngTgZNvr6CDdhv-aPVEzA',
    appId: '1:261106161508:ios:bf49cfd47f2b324cdd4c71',
    messagingSenderId: '261106161508',
    projectId: 'aquaminder-ft',
    storageBucket: 'aquaminder-ft.appspot.com',
    iosBundleId: 'com.example.listaDeCompras',
  );

}